name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # - name: Use Node.js
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: "12.x"

      # - name: Cache Node.js modules
      #   uses: actions/cache@v1
      #   with:
      #     path: ~/.npm
      #     key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.OS }}-node-
      #       ${{ runner.OS }}-

      # - name: Install dependencies
      #   run: npm ci

      # - name: Run Tests:
      #   run: npm test

      - name: Publish to Github Packages Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: joeyvanlierop/portfolio-frontend/frontend
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ github.token }}
          tags: "latest,${{ github.sha }}"
